version: '3'

services:
  # Service pour le conteneur Apache avec PHP
  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - mysql-master
      - mysql-slave
      - grafana

  # Service pour le nœud maître MySQL
  mysql-master:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - ./my.cnf:/etc/mysql/my.cnf
    command: --server-id=1

  # Service pour le nœud esclave MySQL
  mysql-slave:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - ./my_slave.cnf:/etc/mysql/my.cnf
    command: --server-id=2 --master-host=mysql-master --master-port=3306 --master-user=root --master-password=root_password

  # Service pour Grafana
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin_password
